In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("foia_up_to_150k_CA.csv")
df.head()

,LoanAmount,City,State,Zip,NAICSCode,BusinessType,RaceEthnicity,Gender,Veteran,NonProfit,JobsRetained,DateApproved,Lender,CD
0,149999.98,FREEDOM,CA,95019.0,722511.0,Sole Proprietorship,Unanswered,Male Owned,Unanswered,NaN,30.0,04/29/2020,Santa Cruz County Bank,CA - 20
1,149999.98,SANTA CRUZ,CA,95060.0,722511.0,Limited Liability Company(LLC),Unanswered,Male Owned,Non-Veteran,NaN,8.0,04/30/2020,Santa Cruz County Bank,CA - 18
2,149999.00,CALABASAS,CA,91302.0,999990.0,Limited Liability Company(LLC),Unanswered,Unanswered,Unanswered,NaN,12.0,04/29/2020,First Home Bank,CA - 30
3,149999.00,VAN NUYS,CA,91406.0,443142.0,Corporation,Unanswered,Unanswered,Unanswered,NaN,2.0,04/29/2020,First Home Bank,CA - 29
4,149999.00,CYPRESS,CA,90630.0,531210.0,Subchapter S Corporation,Unanswered,Unanswered,Unanswered,NaN,2.0,04/29/2020,First Home Bank,CA - 38